#! /usr/bin/env ruby
require "pg"

require "io/console"

class CLI

  def initialize
    @expense_data = ExpenseData.new
  end

  def run(arguments)
    command = arguments.shift

    case command
    when 'add'
      amount = arguments[0]
      memo = arguments[1]
      abort "You must provide an amount and memo." unless amount && memo
      @expense_data.add_expense(amount, memo)
    when 'delete'
      id = arguments[0]
      @expense_data.delete_expense(id)
    when 'list'
      @expense_data.list_expenses
    when 'search'
      query = arguments[0]
      @expense_data.search_expenses(query)
    when 'clear'
      puts "This will remove all expenses. Are you sure? (y/n)"
      answer = $stdin.getch
      @expense_data.delete_all_expenses if answer == 'y'
    else
      display_help
    end
  end

  def display_help
    puts <<~HELP
      An expense recording system

      Commands:

      add AMOUNT MEMO [DATE] - record a new expense
      clear - delete all expenses
      list - list all expenses
      delete NUMBER - remove expense with id NUMBER
      search QUERY - list expenses with a matching memo field
    HELP
  end
end

class ExpenseData

  def initialize
    @connection = PG.connect(dbname: "expenses")
    setup_schema
  end

  def search_expenses(query)
    sql = "SELECT * FROM expenses WHERE memo ILIKE $1"
    result = @connection.exec_params(sql, ["%#{query}%"])
    display_count(result)
    display_expenses(result) if result.ntuples > 0
  end

  def add_expense(amount, memo)
    date = Date.today
    sql = "INSERT INTO expenses (amount, memo, created_on) VALUES ($1, $2, $3)"
    @connection.exec_params(sql, [amount, memo, date])
  end

  def delete_all_expenses
    @connection.exec("DELETE FROM expenses")
    puts "All expenses have been deleted."
  end

  def delete_expense(id)
    sql = "SELECT * FROM expenses WHERE id = $1"
    result = @connection.exec_params(sql, [id])

    if result.ntuples == 1
      sql = "DELETE FROM expenses WHERE id=$1"
      @connection.exec_params(sql, [id])

      puts "The following expense has been deleted:"
      display_expenses(result)
    else
      puts "There is no expense with the id '#{id}'."
    end
  end

  def list_expenses
    result = @connection.exec("SELECT * FROM expenses")
    display_count(result)
    display_expenses(result) if result.ntuples > 0
  end

  private

  def setup_schema
    result = @connection.exec  <<~SQL
      SELECT COUNT(*) FROM information_schema.tables
      WHERE table_schema = 'public' AND table_name = 'expenses';
    SQL

    if result[0]["count"] == "0"
      @connection.exec <<~SQL
          CREATE TABLE expenses (
          id serial PRIMARY Key,
          amount decimal(6,2) NOT NULL,
          memo text NOT NULL,
          created_on date NOT NULL,
          CONSTRAINT positive_amount CHECK(amount >= 0.01)
        );
      SQL
    end
  end

  def display_expenses(expenses)
    expenses.each do |tuple|
      columns = [ tuple["id"].rjust(3),
                tuple["created_on"].rjust(10),
                tuple["amount"].rjust(12),
                tuple["memo"] ]

      puts columns.join(" | ")
    end
    puts "-" * 50

    total_amount = expenses.field_values("amount").map(&:to_f).reduce(:+)

    puts "Total #{total_amount.to_s.rjust(25)}"
  end

  def display_count(expenses)
    count = expenses.ntuples
    if count > 0
      puts "There are #{count} expense#{"s" if count != 1}."
    else
      puts "There are no expenses."
    end
  end
end

CLI.new.run(ARGV)
